# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Wiki-Toolkit-Plugin-Ping
version:      0.01
version_from: lib/Wiki/Toolkit/Plugin/Ping.pm
installdirs:  site
requires:
    LWP:                           0
    Wiki::Toolkit:                 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
